version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      FLASK_ENV: production
      REDIS_HOST: redis
  redis:
    image: "redis:latest"
    networks:
      - mynetwork
    volumes:
      - redis_data:/data
networks:
  mynetwork:
    driver: bridge
volumes:
  redis_data: